// Python lowering. The same plan the JavaScript target renders (analyze.js), rendered into
// Python instead. The shape is identical — one generator per head predicate, body goals as
// nested loops, the head's `out` arguments yielded one tuple per solution — but Python is
// indentation-scoped, so there are no closing braces: a clause's nest simply dedents back
// to the function body before the next clause. The JSON interpreter is still the reference
// semantics the emitted code must match.
//
// Terms are plain dicts (the same JSON shape), and the generated module leans on a small
// Python runtime (copper_runtime: unify, walk, apply_substitution, make_registry) plus a
// per-target implementation of the harness primitives.

import { analyze } from "./analyze.js"

const pyVar = name => `v_${name}`
const pyGen = name => `lowered_${name}`
const I = n => "    ".repeat(n)

const renderTerm = term =>
  term.type === "var" ? pyVar(term.name) : `{"type": "const", "value": ${JSON.stringify(term.value)}}`
const varLiteral = (name, id) => `{"type": "var", "name": ${JSON.stringify(name)}, "id": ${id}}`

// Emit one clause's statements at function-body indent (level 1) and deeper. Clauses run
// sequentially in the function; Python's lack of block scope is fine because each clause's
// loops fully drain before the next begins.
function emitClause(clause, modes, heads) {
  const hm = modes.get(clause.head.predicate)
  const ids = new Map()
  const varId = name => { if (!ids.has(name)) ids.set(name, ids.size); return ids.get(name) }
  clause.head.args.forEach(a => varId(a.name))

  const lines = []
  const bound = new Set()
  clause.head.args.forEach((a, i) => {
    if (hm[i] === "in") { lines.push(`${I(1)}${pyVar(a.name)} = _in${i}`); bound.add(a.name) }
  })

  clause.body.forEach((goal, depth) => {
    const ind = 1 + depth
    const m = modes.get(goal.predicate)
    if (heads.has(goal.predicate)) {
      const inArgs = goal.args.filter((_, i) => m[i] === "in").map(renderTerm).join(", ")
      const tuple = `_t${depth}`
      lines.push(`${I(ind)}for ${tuple} in ${pyGen(goal.predicate)}(${inArgs}):`)
      let oi = 0
      goal.args.forEach((a, i) => {
        if (m[i] === "out" && a.type === "var") { lines.push(`${I(ind + 1)}${pyVar(a.name)} = ${tuple}[${oi++}]`); bound.add(a.name) }
      })
    } else {
      const reads = []
      const args = goal.args.map((a, i) => {
        if (m[i] === "out" && a.type === "var" && !bound.has(a.name)) {
          reads.push({ name: a.name, id: varId(a.name) })
          bound.add(a.name)
          return varLiteral(a.name, varId(a.name))
        }
        return renderTerm(a)
      })
      const s = `_s${depth}`
      lines.push(`${I(ind)}for ${s} in _solve(${JSON.stringify(goal.predicate)}, [${args.join(", ")}]):`)
      for (const r of reads) lines.push(`${I(ind + 1)}${pyVar(r.name)} = apply_substitution(${varLiteral(r.name, r.id)}, ${s})`)
    }
  })

  const outs = clause.head.args.filter((_, i) => hm[i] === "out").map(a => pyVar(a.name))
  lines.push(`${I(1 + clause.body.length)}yield [${outs.join(", ")}]`)
  return lines.join("\n")
}

export function lowerPython(program, harness, options = {}) {
  const a = analyze(program, harness, options)
  if (!a.feasible)
    return { source: null, metadata: { target: "python", feasibility: "infeasible", caveats: [], reason: a.reason, imports: [], entrypoints: [] } }

  const { caveats, modes, heads, groups } = a
  const runtime = options.runtime ?? "copper_runtime"
  const implementation = options.implementation ?? "copper_impl"

  const blocks = []
  for (const [pred, clauses] of groups) {
    const hm = modes.get(pred)
    const params = clauses[0].head.args.map((_, i) => (hm[i] === "in" ? `_in${i}` : null)).filter(Boolean)
    const body = clauses.map(c => emitClause(c, modes, heads)).join("\n")
    blocks.push(`def ${pyGen(pred)}(${params.join(", ")}):\n${body}`)
  }

  const source = [
    "# Generated by the copper-ilp Python lowering. Do not edit by hand.",
    "# Reference semantics: the JSON interpreter. This code must match it.",
    `from ${runtime} import make_registry, apply_substitution`,
    `from ${implementation} import predicates`,
    "",
    "_reg = make_registry(predicates)",
    "",
    "def _solve(name, args):",
    "    return _reg.solve(name, args, {})",
    "",
    ...blocks
  ].join("\n") + "\n"

  return {
    source,
    metadata: {
      target: "python",
      feasibility: caveats.length ? "caveats" : "ok",
      caveats,
      reason: null,
      imports: [runtime, implementation],
      entrypoints: groups.map(([p]) => pyGen(p))
    }
  }
}
